### ISSUE TITLE
[BUG] Crash when editing timer durations with certain keyboards

### ISSUE THREAD

**Issue by dtkiro** [nsh07/Tomato#120]
**Describe the bug**
When the timer settings are deleted until the end, the app closes automatically. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Timer' option
3. Change the timer settings
4. The app is closed instantly 

**Expected behavior**
The app doesn't close when the settings are changed.

**Screenshots**
https://github.com/user-attachments/assets/05ae717e-348f-4e0b-9977-f207e553facf

**Device (please complete the following information):**
 - Device model: [Redmi Note 11 (spes)]
 - Android version: [Android 13]
 - App version: [v1.6.2]
 - Installed from: [Droid-ify (F-droid)]

**Additional context**
-

**Comment by nsh07** [comment]
I cannot reproduce this crash even after doing what you did in the video. Is there anything else you did that led to this crash?

Currently, when I press backspace while editing the focus time, it just shows "00" instead of crashing

**Comment by jack24254029** [comment]
@nsh07 You can use [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics) to collect exception logs from users' devices.

**Comment by nsh07** [comment]
@jack24254029 but I don't want to use the internet permission in this app, so I cannot use Crashlytics. Is there a way for Crashlytics to export the logs to storage so the user can upload it to GitHub manually?

**Comment by jack24254029** [comment]
@nsh07 You need to write some code that can catch exceptions and write them to a file. Then add a function to export the file to storage or email it, for example.

Could you please explain why you don't want to use the internet permission?

**Comment by dtkiro** [comment]
> I cannot reproduce this crash even after doing what you did in the video. Is there anything else you did that led to this crash?
> 
> Currently, when I press backspace while editing the focus time, it just shows "00" instead of crashing

I'm just using a different keyboard and when I use it on Tomato, the crash occurs.

Is there a way to generate a crash log about the behavior? Using adb or something like that? I can do it if this helps you. :)

**Comment by nsh07** [comment]
@dtkiro yes, you can do it if you have ADB installed on your computer. Turn on USB debugging, connect your phone to your computer make the app crash and then quickly capture a logcat with `adb logcat > logcat.txt`. Let it run for 2 or 3 seconds then press Ctrl + C to stop writing the logcat. Then, upload the `logcat.txt` file here in a comment

@jack24254029 I don't want to use network permission because I want to keep this app completely offline as a guarantee of privacy. The Play Store version uses the internet permission only for loading data from Google Play Billing through RevenueCat. I will find a way to allow the user to export the logs manually. Thanks for the suggestion!

**Comment by MrConorAE** [comment]
I can reproduce, here's a crash log:
```
11-06 11:25:59.473 26815 26815 D AndroidRuntime: Shutting down VM
11-06 11:25:59.474 26815 26815 E AndroidRuntime: FATAL EXCEPTION: main
11-06 11:25:59.474 26815 26815 E AndroidRuntime: Process: org.nsh07.pomodoro, PID: 26815
11-06 11:25:59.474 26815 26815 E AndroidRuntime: java.lang.IndexOutOfBoundsException: start 256, end 255, length 255
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1742)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:695)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:242)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.PartialGapBuffer.toString(Unknown Source:42)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.foundation.text.input.TextFieldState.access$commitEditAsUser(Unknown Source:143)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.ui.spatial.RectList.endBatchEdit(Unknown Source:58)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.AndroidTextInputSession_androidKt$platformSpecificTextInputSession$3$3$textInputSession$1.edit(Unknown Source:15)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.StatelessInputConnection.deleteSurroundingText(Unknown Source:7)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at androidx.compose.ui.text.input.NullableInputConnectionWrapperApi25.deleteSurroundingText(Unknown Source:4)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingText$32(RemoteInputConnectionImpl.java:921)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$YcCflVJvz7SJ4NuA0eRcxDz2wCU(Unknown Source:0)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda44.run(D8$$SyntheticClass:0)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:1041)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.os.Looper.dispatchMessage(Looper.java:315)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:251)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:349)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9041)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
11-06 11:25:59.474 26815 26815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
11-06 11:25:59.474  1066  1140 D CHRE    : @ 509567.986: Parsed nanoapp message from host: app ID 0x476f6f676c00103b endpoint 0x8005 msgType 1 payload size 6
11-06 11:25:59.479  1659 27936 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-06 11:25:59.480  1659  2884 W ActivityTaskManager:   Force finishing activity org.nsh07.pomodoro/.MainActivity
```

**Comment by nsh07** [comment]
@MrConorAE thank you so much for the logs. I was able to find the issue and this crash should be fixed in the next update (most likely this weekend)

**Comment by nsh07** [comment]
This crash should be fixed in [v1.6.3](https://github.com/nsh07/Tomato/releases/tag/v1.6.3). It should be available on F-Droid within a few days. @dtkiro @MrConorAE please add a comment here if this crash still persists in 1.6.3.

**Comment by MrConorAE** [comment]
Argh... installed 1.6.3 and it doesn't appear fixed.

<details>
<summary>New logcat (I think it's the same?) - click to expand</summary>

```
11-02 16:49:56.499 32704 32704 E AndroidRuntime: FATAL EXCEPTION: main
11-02 16:49:56.499 32704 32704 E AndroidRuntime: Process: org.nsh07.pomodoro, PID: 32704
11-02 16:49:56.499 32704 32704 E AndroidRuntime: java.lang.IndexOutOfBoundsException: start 256, end 255, length 255
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1742)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:695)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:242)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.PartialGapBuffer.toString(Unknown Source:42)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.foundation.text.input.TextFieldState.access$commitEditAsUser(Unknown Source:143)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.ui.spatial.RectList.endBatchEdit(Unknown Source:58)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.AndroidTextInputSession_androidKt$platformSpecificTextInputSession$3$3$textInputSession$1.edit(Unknown Source:15)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.StatelessInputConnection.deleteSurroundingText(Unknown Source:7)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at androidx.compose.ui.text.input.NullableInputConnectionWrapperApi25.deleteSurroundingText(Unknown Source:4)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingText$32(RemoteInputConnectionImpl.java:921)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$YcCflVJvz7SJ4NuA0eRcxDz2wCU(Unknown Source:0)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda44.run(D8$$SyntheticClass:0)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:1041)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.os.Looper.dispatchMessage(Looper.java:315)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:251)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:349)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9041)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
11-02 16:49:56.499 32704 32704 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
```
</details>

Interestingly, it seemed to be fixed for the first input field I tried (it turned red), but the second and later fields I tried didn't. Additionally (or maybe this is why it happened?), pressing Backspace in the already-empty field while it was red caused it to turn not-red (but still read "00"), then another Backspace crashed it. I'll try and reproduce with a screen recording.

**Comment by nsh07** [comment]
Please do attach a screen recording of precisely how to reproduce this. If I can reproduce this in my dev environment it would become significantly easier to diagnose the issue. Thanks in advance!

**Comment by guguss-31** [comment]
Fixed for me. 
Thanks 🥳 !

Samsung S21
OneUI 7
Android 15

**Comment by Extner32** [comment]
I'm still having the issue. 
For me, it sometimes crashes and it worked onetime where the input field went red and it didn't crash, I tried again afterwards and then it did crash. 

https://github.com/user-attachments/assets/75e6e944-bf45-4fb7-9a21-d7fdb4756fcd

Nothing phone 3a, android 15

**Comment by nsh07** [comment]
@Extner32 you are running 1.6.2. Can you please install 1.6.3 and confirm if this crash still occurs?

**Comment by Extner32** [comment]
@nsh07 I had the same issue in 1.6.3
Installed it from playstore: 

https://github.com/user-attachments/assets/fbc518ee-e882-4249-9d03-fb65c3aef0f0

**Comment by nsh07** [comment]
@Extner32 I think I have figured out the problem. Can you please install this APK (I just compiled it after fixing this) and see if it still occurs?

https://quickshare.samsungcloud.com/qZ1qMt4eq7SV

**Comment by Extner32** [comment]
@nsh07 Nope, same problem. Maybe you can make the input menu work more like a clock app where you scroll up and down (kinda like in this image:) 

![Image](https://github.com/user-attachments/assets/186997e2-d748-437e-92bb-0fc2d36b57a4)

**Comment by nsh07** [comment]
I am beginning to think this might be an internal issue with the UI library, because it popped out of nowhere without any changes in this repo and I cannot reproduce it at all. I've updated the dependencies, can you please try this (new) APK (one last time 😅) @Extner32 :

https://quickshare.samsungcloud.com/98qFbYzygZ2c

If this is still not fixed in the above APK, I will have to test this issue on more physical devices to find out exactly what is causing it. Unfortunately I cannot make it a vertical rotating clock like you suggested because it will be really annoying to scroll through 90+ digits if you want to set the time to, say 90 minutes lol

**Comment by Extner32** [comment]
I tried it, still the same problem :(
I tried the adb logcat thing you described earlier and here it is:
```--------- beginning of crash
04-12 05:39:55.469   835   835 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 835 (init), pid 835 (init)
04-12 05:39:55.524   835   835 F libc    : crash_dump helper failed to exec, or was killed
10-31 21:48:21.146  4186  4186 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4186 (init), pid 4186 (init)
10-31 21:48:21.175  4186  4186 F libc    : crash_dump helper failed to exec, or was killed
11-06 17:15:50.285  2738  2738 E AndroidRuntime: FATAL EXCEPTION: main
11-06 17:15:50.285  2738  2738 E AndroidRuntime: Process: org.nsh07.pomodoro, PID: 2738
11-06 17:15:50.285  2738  2738 E AndroidRuntime: java.lang.IndexOutOfBoundsException: start 256, end 255, length 255
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1742)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:695)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:242)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.PartialGapBuffer.toString(Unknown Source:42)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at androidx.compose.foundation.text.input.TextFieldState.access$commitEditAsUser(Unknown Source:143)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at okhttp3.internal.http.StatusLine.endBatchEdit(Unknown Source:58)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.AndroidTextInputSession_androidKt$platformSpecificTextInputSession$3$3$textInputSession$1.edit(Unknown Source:15)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at androidx.compose.foundation.text.input.internal.StatelessInputConnection.deleteSurroundingText(Unknown Source:7)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at androidx.compose.ui.text.input.NullableInputConnectionWrapperApi25.deleteSurroundingText(Unknown Source:4)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$deleteSurroundingText$32(RemoteInputConnectionImpl.java:886)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$YcCflVJvz7SJ4NuA0eRcxDz2wCU(Unknown Source:0)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda44.run(D8$$SyntheticClass:0)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:267)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:371)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8837)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:598)
11-06 17:15:50.285  2738  2738 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:896)
```

**Comment by nsh07** [comment]
I CAN REPRODUCE THIS CRASH NOW!!!

The interesting thing is that this crash only occurs when Swiftkey or FUTO is set as the system keyboard. It doesn't happen with Gboard/Samsung Keyboard or a physical keyboard. @Extner32 @MrConorAE @dtkiro Can all of you please confirm what keyboard app you are using?

Edit: here is a list of currently known affected keyboards:
- Swiftkey
- FUTO
- HeliBoard

**Comment by MrConorAE** [comment]
> The interesting thing is that this crash only occurs when Swiftkey is set as the system keyboard. It doesn't happen with Gboard or a physical keyboard.

How interesting - great job working that out! I'm using [FUTO keyboard](https://github.com/futo-org/android-keyboard).

**Comment by Extner32** [comment]
Yup, same. also using FUTO keyboard. It works perfectly with gboard, Nice detective work lol!

**Comment by Surbbd** [comment]
I am using futo keyboard and was going to open an issue. so yeah it crashes for me aswell.

**Comment by dtkiro** [comment]
Hey @nsh07! Great job. I'm happy for you :)

Sorry for the delay to give you an answer, my GitHub app doesn't notify me when I get a response on my own issue comments and when it happens I receive them with a long delay... :(

I'm using HeliBoard keyboard.

**Comment by nsh07** [comment]
Thank you all for reporting this! Now that I can finally test this on my development machine, I can fix and test this bug reliably. I will release an update (most likely today) that resolves this crash.

**Comment by nsh07** [comment]
This crash is now fixed in [v1.6.4](https://github.com/nsh07/Tomato/releases/tag/v1.6.4). Thank you all so much for the cooperation!
